pipeline {

    agent any

    stages {

        stage('Clone') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Ritikasuneriya/reet-flask-app.git'
            }
        }

        stage('Install') {
            steps {
                cd frontend
                sh 'npm install'
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                cd frontend
                pm2 restart express-app || pm2 start server.js \
                --name express-app
                '''
            }
        }

    }

}