pipeline {

    agent any

    stages {

        stage('Clone') {
            steps {
                  git branch: 'main',
                    url: 'https://github.com/Ritikasuneriya/reet-flask-app.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                cd backend
                python3 -m venv venv
                . venv/bin/activate
                pip install -r requirements.txt
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                cd backend
                pm2 restart flask-app || pm2 start app.py \
                --interpreter python3 \
                --name flask-app
                '''
            }
        }

    }

}